"use client";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://oiwxyialfxmsmrzwivlm.supabase.co";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_kqow0_mFC2KoAi9SXdnjKg_fKEp0xG-";
const SESSION_KEY = "afiyah.supabase.session.v1";

export type AfiyahSession = { access_token:string; refresh_token:string; expires_in?:number; expires_at?:number; user:{id:string;email?:string} };
export type QuizResult = {attempt_id:string;score:number;total_questions:number;passed:boolean;best_score:number;reward_created:boolean};

function baseHeaders(token?:string){ return { apikey: SUPABASE_KEY, Authorization: `Bearer ${token || SUPABASE_KEY}`, "Content-Type":"application/json" }; }
export function readSession():AfiyahSession|null{ if(typeof window === "undefined") return null; try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{return null} }
export function saveSession(session:AfiyahSession|null){ if(typeof window === "undefined") return; session?localStorage.setItem(SESSION_KEY,JSON.stringify(session)):localStorage.removeItem(SESSION_KEY); }
export async function signIn(email:string,password:string){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:baseHeaders(),body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||"Sign in failed");saveSession(d);return d as AfiyahSession;}
export async function signUp(email:string,password:string){const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:baseHeaders(),body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||"Sign up failed");if(d.access_token)saveSession(d);return d;}
export function signOut(){saveSession(null)}

async function authed(path:string,init:RequestInit={}){const s=readSession();if(!s?.access_token)throw new Error("Please sign in to save progress across devices.");const r=await fetch(`${SUPABASE_URL}${path}`,{...init,headers:{...baseHeaders(s.access_token),...(init.headers||{})}});if(!r.ok){const t=await r.text();throw new Error(t||`Supabase ${r.status}`)}if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null;}

const moduleSlugs=["niyyah-intention","afiyah-wellbeing","adl-justice","amanah-trust","deen-faith","ihsan-excellence","barakah-increase","sadaqah-giving"];
export async function resolveModule(moduleNo:number){const rows=await authed(`/rest/v1/modules?slug=eq.${moduleSlugs[moduleNo-1]}&select=id,module_number,pass_score,title`);return rows?.[0]}
export async function resolveLesson(moduleId:string,lessonNo:number){const rows=await authed(`/rest/v1/lessons?module_id=eq.${moduleId}&lesson_number=eq.${lessonNo}&select=id,lesson_number,title`);return rows?.[0]}
async function resolvePath(){const rows=await authed(`/rest/v1/learning_paths?slug=eq.afiyah-eight-gift&select=id`);return rows?.[0]}

export async function getLessonProgress(moduleNo:number){const m=await resolveModule(moduleNo);if(!m)return[];const lessons=await authed(`/rest/v1/lessons?module_id=eq.${m.id}&select=id,lesson_number&order=lesson_number.asc`);const s=readSession()!;const p=await authed(`/rest/v1/lesson_progress?user_id=eq.${s.user.id}&lesson_id=in.(${lessons.map((l:any)=>l.id).join(",")})&select=lesson_id,completed,completed_at`);return lessons.map((l:any)=>({...l,completed:p.some((x:any)=>x.lesson_id===l.id&&x.completed)}));}
function isoDay(d:Date){return d.toISOString().slice(0,10)}
export async function markLessonComplete(moduleNo:number,lessonNo:number){const s=readSession()!;const module=await resolveModule(moduleNo);const lesson=await resolveLesson(module.id,lessonNo);const path=await resolvePath();await authed(`/rest/v1/lesson_progress`,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:s.user.id,lesson_id:lesson.id,completed:true,completed_at:new Date().toISOString()})});const rows=await authed(`/rest/v1/academy_enrollments?user_id=eq.${s.user.id}&learning_path_id=eq.${path.id}&select=*`);const current=rows?.[0];const today=isoDay(new Date());const yesterday=isoDay(new Date(Date.now()-86400000));const streak=current?.last_activity_date===today?current.streak_days:current?.last_activity_date===yesterday?(current.streak_days||0)+1:1;const nextLessonNo=Math.min(4,lessonNo+1);const nextLesson=await resolveLesson(module.id,nextLessonNo);const payload={user_id:s.user.id,learning_path_id:path.id,current_week:moduleNo,current_module_id:module.id,current_lesson_id:nextLesson?.id||lesson.id,current_day:Math.min(56,(moduleNo-1)*7+lessonNo),streak_days:streak,best_streak:Math.max(streak,current?.best_streak||0),last_activity_date:today,updated_at:new Date().toISOString()};await authed(`/rest/v1/academy_enrollments`,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});return payload;}

export async function getAttemptStats(moduleNo:number){const s=readSession()!;const module=await resolveModule(moduleNo);const rows=await authed(`/rest/v1/quiz_attempts?user_id=eq.${s.user.id}&module_id=eq.${module.id}&select=id,score,total_questions,passed,submitted_at&order=submitted_at.desc`);return{latest:rows?.[0]||null,best:rows?.length?Math.max(...rows.map((r:any)=>r.score)):null,attempts:rows?.length||0,everPassed:rows?.some((r:any)=>r.passed)||false};}
export async function getQuizQuestionIds(moduleNo:number){const module=await resolveModule(moduleNo);return authed(`/rest/v1/quiz_questions?module_id=eq.${module.id}&select=id,sort_order&order=sort_order.asc,id.asc`)}
export async function submitQuiz(moduleNo:number,answersByNumber:Record<number,string>):Promise<QuizResult>{const module=await resolveModule(moduleNo);const rows=await getQuizQuestionIds(moduleNo);const answers:Record<string,string>={};rows.forEach((q:any,index:number)=>answers[q.id]=answersByNumber[index+1]||"");return authed(`/rest/v1/rpc/academy_submit_quiz_attempt`,{method:"POST",body:JSON.stringify({p_module_id:module.id,p_answers:answers})});}

export async function getPendingReward(moduleNo:number){const s=readSession()!;const module=await resolveModule(moduleNo);const rows=await authed(`/rest/v1/academy_rewards?user_id=eq.${s.user.id}&module_id=eq.${module.id}&reward_type=eq.module_pass&select=*&limit=1`);return rows?.[0]||null}
export async function resolveReward(rewardId:string,choice:"kept"|"given"){const s=readSession()!;const rows=await authed(`/rest/v1/academy_rewards?id=eq.${rewardId}&user_id=eq.${s.user.id}&select=*`);const reward=rows?.[0];if(!reward)throw new Error("Reward not found");if(reward.disposition!=="pending")return reward;await authed(`/rest/v1/academy_rewards?id=eq.${rewardId}&user_id=eq.${s.user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({disposition:choice,resolved_at:new Date().toISOString()})});if(choice==="given")await authed(`/rest/v1/infinity_well_contributions`,{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:s.user.id,reward_id:rewardId,points:reward.points})});return{...reward,disposition:choice};}

export async function getDashboardState(){const s=readSession()!;const [enrollmentRows,rewards,well,eight]=await Promise.all([authed(`/rest/v1/academy_enrollments?user_id=eq.${s.user.id}&select=*&limit=1`),authed(`/rest/v1/academy_rewards?user_id=eq.${s.user.id}&select=points,disposition,reward_type,module_id`),authed(`/rest/v1/infinity_well_contributions?user_id=eq.${s.user.id}&select=points`),authed(`/rest/v1/my_eight?owner_user_id=eq.${s.user.id}&select=*&order=slot_number.asc`)]);const enrollment=enrollmentRows?.[0]||null;let lessonNumber=1;if(enrollment?.current_lesson_id){const lr=await authed(`/rest/v1/lessons?id=eq.${enrollment.current_lesson_id}&select=lesson_number&limit=1`);lessonNumber=lr?.[0]?.lesson_number||1}const kept=(rewards||[]).filter((r:any)=>r.disposition==="kept").reduce((a:number,r:any)=>a+r.points,0);const given=(well||[]).reduce((a:number,r:any)=>a+r.points,0);const week=enrollment?.current_week||1;return{enrollment,kept,given,myEight:eight||[],resume:{week,lessonNumber,href:`/afiyah-gift/module/${week}/lesson/${lessonNumber}`}};}
export async function saveMyEightSlot(slot_number:number,pillar:string,invite_email:string){const s=readSession()!;return authed(`/rest/v1/my_eight`,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({owner_user_id:s.user.id,slot_number,pillar,invite_email,status:"invited",current_week:1,progress_percent:0})});}
export async function claimMyEightInvite(ownerUserId:string,slotNumber:number){return authed(`/rest/v1/rpc/claim_my_eight_invite`,{method:"POST",body:JSON.stringify({p_owner_user_id:ownerUserId,p_slot_number:slotNumber})});}
