import Link from "next/link";
import { Flame, Gift, Languages, LockKeyhole, Sparkles, Users } from "lucide-react";
import { AFIYAH_GIFT_MODULES, GIFT_PROGRAM_RULES } from "@/data/afiyah-gift-modules";
import { ARABIC_DOUBLE_REWARD_COPY } from "@/data/afiyah-language-tracks";

const progress = [100, 50, 0, 0, 0, 0, 0, 0];

export default function AfiyahGiftPage() {
  return <main className="min-h-screen bg-[#061B26] px-4 py-8 text-[#F8F3E9] lg:px-8"><div className="mx-auto max-w-5xl">
    <section className="rounded-[32px] border border-[#AD8633]/30 bg-[#003629]/45 p-6 shadow-2xl lg:p-8"><div className="flex items-center gap-3 text-[#D6B46D]"><Gift className="h-6 w-6"/><span className="text-xs font-bold uppercase tracking-[.24em]">A gift from Afiyah</span></div><div className="mt-4 grid gap-6 lg:grid-cols-[1.5fr_.8fr] lg:items-end"><div><h1 className="font-serif text-4xl lg:text-6xl">The Afiyah Eight</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65 lg:text-base">Eight pillars. Eight modules. Eight weeks. Open the actual lessons, pass each mastery quiz at 90% or higher, choose KEEP or GIVE, and carry the learning to My Eight.</p></div><div className="rounded-2xl border border-[#AD8633]/25 bg-black/15 p-4"><div className="text-xs uppercase tracking-[.2em] text-[#D6B46D]">Journey progress</div><div className="mt-2 flex items-end justify-between"><strong className="font-serif text-4xl">19%</strong><span className="text-xs text-white/50">Week 2 · Day 10/56</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[19%] rounded-full bg-[#D6B46D]"/></div></div></div>
      <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-2xl bg-black/15 p-4"><div className="text-xs text-white/40">Streak</div><div className="mt-1 flex items-center gap-2 font-serif text-2xl"><Flame className="text-[#D6B46D]"/>5 days</div></div><div className="rounded-2xl bg-black/15 p-4"><div className="text-xs text-white/40">Best score</div><div className="mt-1 font-serif text-2xl">10/10</div></div><div className="rounded-2xl bg-black/15 p-4"><div className="text-xs text-white/40">Wallet</div><div className="mt-1 font-serif text-2xl">8∞</div></div><Link href="/afiyah-gift/my-eight" className="rounded-2xl border border-[#D6B46D]/25 bg-[#AD8633]/10 p-4"><div className="flex items-center gap-2 text-xs text-[#D6B46D]"><Users className="h-4 w-4"/>My Eight</div><div className="mt-1 font-serif text-2xl">7/8</div></Link></div>
    </section>

    <section className="mt-6 rounded-3xl border border-[#D6B46D]/30 bg-gradient-to-r from-[#003629] to-[#0B3540] p-5 lg:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#AD8633]/20 text-[#D6B46D]"><Languages/></div><div><div className="flex items-center gap-2"><h2 className="font-serif text-2xl">العربية · Arabic</h2><Sparkles className="h-4 w-4 text-[#D6B46D]"/></div><p className="mt-1 text-sm text-white/60">{ARABIC_DOUBLE_REWARD_COPY.subtitle}</p></div></div><div className="flex gap-2 text-sm font-bold"><span className="rounded-full border border-[#D6B46D]/35 px-4 py-2 text-[#D6B46D]">{ARABIC_DOUBLE_REWARD_COPY.infinity}</span><span className="rounded-full border border-[#D6B46D]/35 px-4 py-2 text-[#D6B46D]">{ARABIC_DOUBLE_REWARD_COPY.amanah}</span></div></div></section>

    <section className="mt-6 grid gap-4 md:grid-cols-2">{AFIYAH_GIFT_MODULES.map((module,index)=>{const pct=progress[index]??0; const locked=index>1; return <article key={module.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-5 transition hover:-translate-y-0.5 hover:border-[#AD8633]/40"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-[#AD8633]">Week {module.id} · Module {String(module.id).padStart(2,"0")}</div><div className="mt-2 flex items-baseline gap-2"><span className="font-serif text-3xl text-[#D6B46D]">{module.pillarAr}</span><span className="font-serif text-xl">{module.pillar}</span><span className="text-xs text-white/45">{module.english}</span></div></div>{locked?<LockKeyhole className="h-5 w-5 text-white/25"/>:<span className="rounded-full bg-[#AD8633]/15 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-[#D6B46D]">{pct===100?'Passed':'Active'}</span>}</div><h3 className="mt-4 font-serif text-2xl">{module.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-white/55">{module.promise}</p><div className="mt-5 flex items-center justify-between text-xs text-white/45"><span>{module.lessonCount} lessons</span><span>{module.quizQuestions} questions</span><span>{module.passPercent}% pass</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#D6B46D]" style={{width:`${pct}%`}}/></div><div className="mt-2 text-right text-xs font-bold text-[#D6B46D]">{pct}%</div><Link href={locked?'#':`/afiyah-gift/module/${module.id}`} aria-disabled={locked} className={`mt-4 block rounded-2xl px-4 py-3 text-center text-xs font-bold uppercase tracking-[.16em] ${locked?'cursor-not-allowed bg-white/5 text-white/20':'bg-[#AD8633] text-[#061B26] hover:bg-[#D6B46D]'}`}>{locked?'Complete previous module':pct===100?'Review lessons':'Continue lessons'}</Link></article>})}</section>

    <section className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-[#5D234F]/50 bg-[#5D234F]/15 p-6"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#D6B46D]">Infinity Well</div><div className="mt-2 font-serif text-4xl">56 / 88∞</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[64%] bg-[#D6B46D]"/></div><p className="mt-3 text-xs leading-5 text-white/45">GIVE rewards pour here. KEEP rewards remain on the learner dashboard.</p></div><Link href="/afiyah-gift/my-eight" className="rounded-3xl border border-[#AD8633]/30 bg-[#003629]/45 p-6"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#D6B46D]">∞ × ∞</div><div className="mt-2 font-serif text-4xl">My Eight</div><p className="mt-3 text-sm leading-6 text-white/50">See eight women, eight pillars, week numbers, progress rings and multiplication status.</p></Link></section>

    <p className="mx-auto mt-8 max-w-3xl text-center text-xs leading-6 text-white/35">Pass mark {GIFT_PROGRAM_RULES.passPercent}%. Progress, quiz attempts, best score, reward disposition, streak and My Eight now have a Supabase persistence model. Production curriculum wording remains governed by the approved source packs.</p>
  </div></main>;
}
