import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpenCheck } from "lucide-react";
import { AFIYAH_GIFT_MODULES } from "@/data/afiyah-gift-modules";

const lessonCopy = [
  { title:"Learn", eyebrow:"Understand", body:"Start with the meaning of the pillar. Read slowly, connect it to one real decision in your life, and identify where the principle changes the way you would normally act.", prompt:"What is one idea here you want to remember tomorrow?" },
  { title:"Apply", eyebrow:"Practice", body:"Knowledge becomes useful when it changes behaviour. Choose one small action that expresses this pillar this week. Keep it specific enough that you can actually complete it.", prompt:"What will you do, for whom, and by when?" },
  { title:"Reflect", eyebrow:"Notice", body:"Think of a recent moment when this pillar was present, missing, or difficult. Reflection is not scored; it helps you notice patterns before the mastery quiz.", prompt:"What would you repeat or change next time?" },
  { title:"Prepare for Mastery", eyebrow:"Review", body:"Review the key ideas from this week. The final assessment has 10 questions and requires 9 correct answers. If you do not pass, your best score remains and you can learn, retry and improve.", prompt:"Which idea still feels least clear? Revisit it before the quiz." },
];

export default function LessonPage({params}:{params:{moduleId:string;lessonNo:string}}){const module=AFIYAH_GIFT_MODULES.find(m=>m.id===Number(params.moduleId))??AFIYAH_GIFT_MODULES[0]; const n=Math.min(4,Math.max(1,Number(params.lessonNo))); const lesson=lessonCopy[n-1]; return <main className="min-h-screen bg-[#061B26] px-4 py-8 text-[#F8F3E9]"><article className="mx-auto max-w-2xl"><Link href={`/afiyah-gift/module/${module.id}`} className="inline-flex items-center gap-2 text-sm text-[#D6B46D]"><ArrowLeft className="h-4 w-4"/>Module {module.id}</Link><div className="mt-8 text-xs font-bold uppercase tracking-[.25em] text-[#AD8633]">{lesson.eyebrow} · Lesson {n}/4</div><div className="mt-3 flex items-baseline gap-3"><span className="font-serif text-5xl text-[#D6B46D]">{module.pillarAr}</span><span className="font-serif text-2xl">{module.pillar} · {module.english}</span></div><h1 className="mt-7 font-serif text-5xl">{lesson.title}</h1><div className="mt-8 rounded-[32px] border border-white/10 bg-white/[.035] p-6 lg:p-8"><BookOpenCheck className="h-7 w-7 text-[#D6B46D]"/><p className="mt-5 text-lg leading-9 text-white/75">{lesson.body}</p><div className="mt-7 rounded-2xl border border-[#AD8633]/25 bg-[#003629]/60 p-5"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-[#D6B46D]">Reflection</div><p className="mt-2 font-serif text-xl">{lesson.prompt}</p></div></div><div className="mt-6 flex items-center justify-between text-xs text-white/35"><span>Progress saves to your account when signed in.</span><span>{n}/4</span></div><Link href={n<4?`/afiyah-gift/module/${module.id}/lesson/${n+1}`:`/afiyah-gift/module/${module.id}/quiz`} className="mt-4 flex items-center justify-center gap-2 rounded-2xl bg-[#AD8633] px-5 py-4 text-xs font-bold uppercase tracking-[.18em] text-[#061B26]">{n<4?'Complete & continue':'Continue to quiz'}<ArrowRight className="h-4 w-4"/></Link><p className="mt-6 text-center text-[11px] leading-5 text-white/30">Prototype lesson shell. Production lesson wording should be populated from the approved Islamic University / Afiyah curriculum sources rather than generic filler.</p></article></main>}
